version: '3.8'

services:
  postgres_container:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: TiendaVirtual
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network
    ports:
      - "5432:5432"

  spring_boot_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    depends_on:
      - postgres_container
    networks:
      - ecommerce_network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/TiendaVirtual
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

networks:
  ecommerce_network:
    driver: bridge

volumes:
  postgres_data:
